import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "../styles";
import { TailoringRun } from "../../schemas";

interface Props {
    run: TailoringRun;
}

export const ComparisonPDFTemplate = ({ run }: Props) => {
    const { resumeProfile, jdProfile, originalMatch, tailoredMatch, tailoredResume, gapAnalysis } = run;

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                {/* Header */}
                <View style={styles.header}>
                    <Text style={styles.title}>Resume Tailoring Comparison</Text>
                    <Text style={styles.subtitle}>
                        Target: {jdProfile.jobTitle} at {jdProfile.company}
                    </Text>
                    <Text style={styles.date}>Generated on {new Date().toLocaleDateString()}</Text>
                </View>

                {/* Scores */}
                <View style={styles.scoreGrid}>
                    <View style={styles.scoreItem}>
                        <Text style={styles.scoreLabel}>ORIGINAL SCORE</Text>
                        <Text style={styles.scoreValue}>{originalMatch.overallScore}%</Text>
                    </View>
                    <View style={styles.scoreItem}>
                        <Text style={styles.scoreLabel}>TAILORED SCORE</Text>
                        <Text style={styles.scoreValue}>{tailoredMatch?.overallScore ?? "N/A"}%</Text>
                    </View>
                    <View style={styles.scoreItem}>
                        <Text style={styles.scoreLabel}>IMPROVEMENT</Text>
                        <Text style={styles.scoreValue}>
                            {tailoredMatch ? tailoredMatch.overallScore - originalMatch.overallScore : 0}%
                        </Text>
                    </View>
                </View>

                {/* Gap Summary */}
                {gapAnalysis && gapAnalysis.gaps.length > 0 && (
                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Key Gaps Addressed</Text>
                        <View style={styles.skillList}>
                            {gapAnalysis.gaps.map((gap, i) => (
                                <View key={i} style={[styles.skillBadge, gap.importance === "high" ? { backgroundColor: "#fee2e2" } : {}]}>
                                    <Text>{gap.name} ({gap.importance})</Text>
                                </View>
                            ))}
                        </View>
                    </View>
                )}

                {/* Bullet Comparison */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Experience Comparison</Text>
                    <View style={styles.comparisonRow}>
                        <View style={styles.comparisonCol}>
                            <Text style={styles.colHeader}>Original Content</Text>
                        </View>
                        <View style={styles.comparisonCol}>
                            <Text style={styles.colHeader}>Tailored Content</Text>
                        </View>
                    </View>

                    {tailoredResume?.tailoredExperience.map((exp, eIdx) => (
                        <View key={eIdx}>
                            <Text style={{ fontSize: 11, fontWeight: "bold", marginVertical: 10, color: "#475569" }}>
                                {exp.company} — {exp.title}
                            </Text>
                            {exp.bullets.map((bullet, bIdx) => (
                                <View key={bIdx} style={styles.comparisonRow} wrap={false}>
                                    <View style={styles.comparisonCol}>
                                        <Text style={styles.originalBullet}>• {bullet.original}</Text>
                                    </View>
                                    <View style={styles.comparisonCol}>
                                        <Text style={styles.tailoredBullet}>• {bullet.tailored}</Text>
                                        <Text style={styles.reason}>Why: {bullet.changeReason}</Text>
                                    </View>
                                </View>
                            ))}
                        </View>
                    ))}
                </View>

                {/* Disclaimer */}
                <View style={styles.disclaimer} fixed>
                    <Text>
                        AI-ASSISTED DOCUMENT: This tailoring was generated by Resume Shapeshifter using LLMs.
                        Verification is mandatory. Do not include experience you do not possess.
                        The scores are relative to detected JD keywords and do not guarantee selection.
                    </Text>
                </View>
            </Page>
        </Document>
    );
};
